<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse Services', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"gap":"no","elementId":"guten-WaJOvA","verticalAlign":"flex-start","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"10","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"right":"35","left":"35","bottom":"60","top":"80"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20"}}},"zIndex":{"Desktop":"0"}} -->
<div class="section-wrapper" data-id="WaJOvA"><section class="wp-block-gutenverse-section guten-element guten-section guten-WaJOvA layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":44,"Tablet":100,"Mobile":null},"sticky":{"Desktop":false,"Tablet":false},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"sectionVerticalAlign":"flex-start","elementId":"guten-ySC7lR","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"40"}}},"zIndex":{"Desktop":"0"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ySC7lR"><div class="guten-column-wrapper" data-id="ySC7lR"><!-- wp:gutenverse/icon {"elementId":"guten-tfB6SR","icon":"gtn gtn-square-solid","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-tfB6SR guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-square-solid"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-guoNjF","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Services","focusText":"/  Our Expertise","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"25","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"15"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"zIndex":{"Desktop":"0"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-advanced-heading guten-guoNjF"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Services</span><span class="heading-focus">/  Our Expertise</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-2h3Xgt","alignText":{"Desktop":"flex-start"},"text":"Choose what matters to your ","focusText":"{Business}","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"FvbTdd","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"110","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"advanceAnimation":{"actions":[]}} -->
<div class="guten-element guten-advanced-heading guten-2h3Xgt"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Choose what matters to your </span><span class="heading-focus">{Business}</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/button {"elementId":"guten-vEgutH","content":"Learn More","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"right"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"17","right":"28","bottom":"19","left":"28"}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"26","bottom":"17","left":"26"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0},"gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":false,"opacity":1,"id":5,"offset":"0.140"},{"color":"rgba(255, 74, 56, 1)","active":true,"opacity":1,"id":3,"offset":"0.725"},{"color":"rgba(255, 74, 56, 1)","active":false,"id":4,"offset":"0.928"},{"color":"rgba(0, 0, 0, 1)","active":false,"opacity":1,"id":2,"offset":"0.932"}],"gradientType":"linear","gradientAngle":"130"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"13","bottom":"13","left":"13"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"icon":"gtn gtn-arrow-right-line","iconPosition":"after","iconSpacing":{"Desktop":"10"},"iconSize":{"Desktop":{"point":"30","unit":"px"}},"background":{"type":"default","gradientColor":[{"color":"rgb(49, 207, 180)","active":false,"id":1,"offset":"0.000"},{"color":"rgba(0, 0, 0, 1)","opacity":1,"active":true,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":[]},"all":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"hideDesktop":false,"hideTablet":true,"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"C3z2EQ","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"theme-1"},"hoverTextColor":{"type":"variable","id":"theme-1"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-vEgutH hide-tablet"><a class="guten-button slow guten-button-sm" href="#"><span>Learn More</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":56,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-cSbLmw","margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":"30"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}},"cursorEffect":{"defaultStyle":"style1","type":"default","show":false}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cSbLmw"><div class="guten-column-wrapper" data-id="cSbLmw"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-EO3auF","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}},"top":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"icon":"","disableDefault":false,"img":[],"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"imageSize":{"point":"20","unit":"px"},"textBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"text":"click","textColor":{"r":0,"g":0,"b":0,"a":1},"padding":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"ZIndex":"","imageWidth":{"point":"","unit":"px"},"delay":false,"defaultSpeed":{"point":"0.4","unit":"s"},"imageHeight":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="EO3auF"><section class="wp-block-gutenverse-section guten-element guten-section guten-EO3auF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-X5xJR7","hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-X5xJR7"><div class="guten-column-wrapper" data-id="X5xJR7"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-kY3P2q","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"01","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-kY3P2q guten-data" data-id="kY3P2q"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">01</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":70},"sectionVerticalAlign":"center","elementId":"guten-PdWjHc"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PdWjHc"><div class="guten-column-wrapper" data-id="PdWjHc"><!-- wp:gutenverse/heading {"elementId":"guten-SdqFtE","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-SdqFtE">Digital Strategy</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":30},"sectionVerticalAlign":"center","elementId":"guten-GAzrfn","verticalAlign":{"Desktop":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GAzrfn"><div class="guten-column-wrapper" data-id="GAzrfn"><!-- wp:gutenverse/icon {"elementId":"guten-DqxDdz","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-DqxDdz guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-elVGir","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"text":"click","textBorder":{"radius":{"Desktop":[]}},"textColor":{"r":4,"g":4,"b":4,"a":1},"background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1}},"typography":{"font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"20","unit":"px"}},"style":"italic"},"img":[],"delay":false,"defaultSpeed":{"point":"0.4","unit":"s"},"ZIndex":"","imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"imageWidth":{"point":"","unit":"px"},"imageHeight":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="elVGir"><section class="wp-block-gutenverse-section guten-element guten-section guten-elVGir layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-aEmswl","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-aEmswl"><div class="guten-column-wrapper" data-id="aEmswl"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-fKSL9A","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"02","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-fKSL9A guten-data" data-id="fKSL9A"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">02</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":70},"sectionVerticalAlign":"center","elementId":"guten-trmet3"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-trmet3"><div class="guten-column-wrapper" data-id="trmet3"><!-- wp:gutenverse/heading {"elementId":"guten-dZnz3N","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-dZnz3N">Branding Identity</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":30},"sectionVerticalAlign":"center","elementId":"guten-HrajS3","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-HrajS3"><div class="guten-column-wrapper" data-id="HrajS3"><!-- wp:gutenverse/icon {"elementId":"guten-b40dDV","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-b40dDV guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4vBWt4","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"img":[],"delay":false,"defaultSpeed":{"point":"","unit":"s"},"ZIndex":"","imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"imageWidth":{"point":"","unit":"px"},"imageHeight":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="4vBWt4"><section class="wp-block-gutenverse-section guten-element guten-section guten-4vBWt4 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-VGKcbs","hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-VGKcbs"><div class="guten-column-wrapper" data-id="VGKcbs"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-oDZLLy","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"03","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-oDZLLy guten-data" data-id="oDZLLy"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">03</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":70},"sectionVerticalAlign":"center","elementId":"guten-QHEEcD"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-QHEEcD"><div class="guten-column-wrapper" data-id="QHEEcD"><!-- wp:gutenverse/heading {"elementId":"guten-7nOhAu","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-7nOhAu">Digital Product</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":30},"sectionVerticalAlign":"center","elementId":"guten-ocgUqF","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ocgUqF"><div class="guten-column-wrapper" data-id="ocgUqF"><!-- wp:gutenverse/icon {"elementId":"guten-EvGTvx","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconAlign":{"Desktop":null},"iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-EvGTvx guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-nnKPK8","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"img":[],"ZIndex":"","delay":false,"defaultSpeed":{"point":"","unit":"s"},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"imageHeight":{"point":"","unit":"px"},"imageWidth":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="nnKPK8"><section class="wp-block-gutenverse-section guten-element guten-section guten-nnKPK8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-J7KhP3","hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-J7KhP3"><div class="guten-column-wrapper" data-id="J7KhP3"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-xItjsR","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"04","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-xItjsR guten-data" data-id="xItjsR"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">04</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":80},"sectionVerticalAlign":"center","elementId":"guten-BfZPBm"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-BfZPBm"><div class="guten-column-wrapper" data-id="BfZPBm"><!-- wp:gutenverse/heading {"elementId":"guten-nYSPlq","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-nYSPlq">Content Marketing</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":20},"sectionVerticalAlign":"center","elementId":"guten-ToHewR","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ToHewR"><div class="guten-column-wrapper" data-id="ToHewR"><!-- wp:gutenverse/icon {"elementId":"guten-7DGe79","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-7DGe79 guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-gyUgjH","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"img":[],"ZIndex":"","delay":false,"defaultSpeed":{"point":"","unit":"s"},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"imageHeight":{"point":"","unit":"px"},"imageWidth":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="gyUgjH"><section class="wp-block-gutenverse-section guten-element guten-section guten-gyUgjH layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-10pAfi","hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-10pAfi"><div class="guten-column-wrapper" data-id="10pAfi"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-y1KHNZ","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"05","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-y1KHNZ guten-data" data-id="y1KHNZ"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">05</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":80},"sectionVerticalAlign":"center","elementId":"guten-oufi6G"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-oufi6G"><div class="guten-column-wrapper" data-id="oufi6G"><!-- wp:gutenverse/heading {"elementId":"guten-l6bMv0","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-l6bMv0">Web Development</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":20},"sectionVerticalAlign":"center","elementId":"guten-i62Fk5","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-i62Fk5"><div class="guten-column-wrapper" data-id="i62Fk5"><!-- wp:gutenverse/icon {"elementId":"guten-rGoEQt","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-rGoEQt guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-vSg4n8","verticalAlign":"center","background":{"videoPlayOnMobile":false,"type":"default","color":{"type":"variable","id":"theme-1"}},"backgroundHover":{"type":"gradient","gradientColor":[{"color":"rgba(0, 0, 0, 1)","active":true,"opacity":1,"id":1,"offset":"0.643"},{"color":"rgba(81, 7, 115, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":"179"},"border":{"radius":{"Desktop":[]},"top":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"borderHover":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":81,"g":7,"b":115,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"35","bottom":"35"}},"Tablet":{"unit":"px","dimension":{"top":"28","bottom":"28"}},"Mobile":{"unit":"px","dimension":{"top":"30","bottom":"30"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"400"},"cursorEffect":{"defaultStyle":"style1","type":"image","show":false,"img":[],"ZIndex":"","delay":false,"defaultSpeed":{"point":"","unit":"s"},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"imageHeight":{"point":"","unit":"px"},"imageWidth":{"point":"","unit":"px"}}} -->
<div class="section-wrapper" data-id="vSg4n8"><section class="wp-block-gutenverse-section guten-element guten-section guten-vSg4n8 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":12.4,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-mT2Cre","hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-mT2Cre"><div class="guten-column-wrapper" data-id="mT2Cre"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-06fvmW","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"06","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-06fvmW guten-data" data-id="06fvmW"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">06</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":71.8,"Mobile":70},"sectionVerticalAlign":"center","elementId":"guten-ItCJcL"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ItCJcL"><div class="guten-column-wrapper" data-id="ItCJcL"><!-- wp:gutenverse/heading {"elementId":"guten-CiACQn","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-CiACQn">PPC Advertising</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":15.8,"Mobile":30},"sectionVerticalAlign":"center","elementId":"guten-uLRfAX","horizontalAlign":{"Desktop":"flex-end","Mobile":"flex-end"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uLRfAX"><div class="guten-column-wrapper" data-id="uLRfAX"><!-- wp:gutenverse/icon {"elementId":"guten-8LkAVB","mouseMoveEffect":{"enable":false},"icon":"gtn gtn-arrow-down-right-line","iconColorOne":{"r":255,"g":255,"b":255,"a":0},"iconSize":{"Desktop":{"point":"26","unit":"px"},"Tablet":{"point":"22","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"iconPadding":{"Desktop":"12","Tablet":"10","Mobile":"10"},"iconColorTwo":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverOne":{"r":255,"g":255,"b":255,"a":1},"iconColorHoverTwo":{"r":0,"g":0,"b":0,"a":1},"iconShape":"circle","url":"#","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"all":{"type":"solid","width":"1","color":{"r":110,"g":111,"b":110,"a":1}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"9"},"positioningType":{"Desktop":"inline"},"transform":{"duration":"0.4","ease":"","transformOrigin":{"Desktop":"center center"}}} -->
<div class="wp-block-gutenverse-icon guten-element guten-8LkAVB guten-icon"><a class="guten-icon-wrapper circle stacked" href="#"><i class="gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/icon --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
