<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse Projects', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-QsPJUR","verticalAlign":"flex-start","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="QsPJUR"><section class="wp-block-gutenverse-section guten-element guten-section guten-QsPJUR layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-V2Oqw1","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"120","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80"}}},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-V2Oqw1"><div class="guten-column-wrapper" data-id="V2Oqw1"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-aBe8bB","verticalAlign":"flex-start","border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"100"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="aBe8bB"><section class="wp-block-gutenverse-section guten-element guten-section guten-aBe8bB layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sectionVerticalAlign":"flex-start","elementId":"guten-l0FJjP","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-l0FJjP"><div class="guten-column-wrapper" data-id="l0FJjP"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-JROGcF","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}}},"padding":{"Desktop":{"unit":"%","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}}}} -->
<div class="section-wrapper" data-id="JROGcF"><section class="wp-block-gutenverse-section guten-element guten-section guten-JROGcF layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-uP6URF","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uP6URF"><div class="guten-column-wrapper" data-id="uP6URF"><!-- wp:gutenverse/icon {"elementId":"guten-7AuC28","icon":"gtn gtn-square-solid","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-7AuC28 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-square-solid"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-k1jHnO","titleTag":"h3","text":"Projects","focusText":"/ Works We Have Done","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-advanced-heading guten-k1jHnO"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Projects</span><span class="heading-focus">/ Works We Have Done</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-pYGLX7","alignText":{"Desktop":"flex-start"},"text":"We always build stunning visual experiences and fully integrated digital product","focusText":" to solve your problem.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"FvbTdd","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"895","unit":"px"},"Tablet":{"point":"665","unit":"px"}},"advanceAnimation":{"actions":[]}} -->
<div class="guten-element guten-advanced-heading guten-pYGLX7 animated guten-element-hide desktop-fadeInLeft"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">We always build stunning visual experiences and fully integrated digital product</span><span class="heading-focus"> to solve your problem.</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-M9Io6p","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60"}},"Tablet":{"unit":"px","dimension":{"bottom":"0","right":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"left":"52","top":"","right":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"left":"0"}}},"hideDesktop":false} -->
<div class="section-wrapper" data-id="M9Io6p"><section class="wp-block-gutenverse-section guten-element guten-section guten-M9Io6p layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100},"elementId":"guten-TkHiNR","horizontalAlign":{"Desktop":"flex-end"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"55","right":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","right":""}},"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TkHiNR"><div class="guten-column-wrapper" data-id="TkHiNR"><!-- wp:gutenverse/text-editor {"elementId":"guten-ywHvGC","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"50"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"point":"532","unit":"px"}}} -->
<div class="guten-element gutenverse-text-editor guten-ywHvGC"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"20px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:20px;margin-left:0px">Inventore perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam Perspiciatis unde omnis iste  accusantium natus error sit voluptatem atque. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Eaque ipsa quae ab illo inventore veritatis et quasi architecto. Perspiciatis unde omnis iste natus error doloremque sit voluptatem dolores.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-kQ30SQ","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} -->
<div class="section-wrapper" data-id="kQ30SQ"><section class="wp-block-gutenverse-section guten-element guten-section guten-kQ30SQ slow layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":52,"Tablet":50},"elementId":"guten-OpjdMH","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"85"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"40"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-OpjdMH"><div class="guten-column-wrapper" data-id="OpjdMH"><!-- wp:gutenverse/wrapper {"elementId":"guten-70sV6k","displayType":"block","url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-70sV6k block with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="70sV6k"><!-- wp:gutenverse/image-box {"elementId":"guten-LmDK5M","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":14,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":169,"width":300,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"large":{"height":576,"width":1024,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp","height":1080,"width":1920,"orientation":"landscape"}}},"size":"full"},"imageAlt":"watch-branding-design","imagePadding":{"Desktop":[],"Tablet":[]},"imageMargin":{"Desktop":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"0","left":"0"}},"imageHeight":{"Desktop":{"point":"400","unit":"px"},"Tablet":{"point":"220","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"},"lazyLoad":true} -->
<div class="guten-LmDK5M guten-image-box guten-element style-default"><a class="" href="#"><div class="inner-container"><div class="image-box-header"><img class="gutenverse-image-box-filled" src="' . esc_url( OIGNY_LITE_URI ) . 'assets/img/watch-hand-plastic-time-ice-metal-635899-pxhere.com_.webp" height="1080" width="1920" alt="watch-branding-design" loading="lazy"/></div><div class="image-box-body"><div class="body-inner"></div></div></div></a></div>
<!-- /wp:gutenverse/image-box -->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-PAUN9k","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}}} -->
<div class="section-wrapper" data-id="PAUN9k"><section class="wp-block-gutenverse-section guten-element guten-section guten-PAUN9k layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-odZb7G"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-odZb7G"><div class="guten-column-wrapper" data-id="odZb7G"><!-- wp:gutenverse/star-rating {"elementId":"guten-pNJOPn","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"6CnHAN","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} -->
<div class="guten-element guten-star-rating guten-pNJOPn"><div class="rating-wrapper"><span class="rating-title">4.4/5</span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating -->

<!-- wp:gutenverse/heading {"elementId":"guten-fadZRB","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"iDPt6e","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-fadZRB">Icewatch.</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-K9oNEI","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-K9oNEI"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Branding Design</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48,"Tablet":50,"Mobile":null},"elementId":"guten-54aVNW","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","bottom":"","top":"100"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}},"Tablet":{"unit":"px","dimension":{"left":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-54aVNW"><div class="guten-column-wrapper" data-id="54aVNW"><!-- wp:gutenverse/wrapper {"elementId":"guten-i8k9Cj","displayType":"block","margin":{"Desktop":{"unit":"px","dimension":{"right":"55","left":"50"}},"Tablet":{"unit":"px","dimension":{"right":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-i8k9Cj block with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="i8k9Cj"><!-- wp:gutenverse/image-box {"elementId":"guten-3VVi5m","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":18,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.jpg","orientation":"landscape"},"medium":{"height":300,"width":240,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.jpg","orientation":"portrait"},"large":{"height":1024,"width":819,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.jpg","orientation":"portrait"},"full":{"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.jpg","height":1800,"width":1440,"orientation":"portrait"}}},"size":"full"},"imageAlt":"durovo-seo-booster","imagePadding":{"Desktop":[],"Tablet":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15"}},"imageHeight":{"Desktop":{"point":"600","unit":"px"},"Tablet":{"point":"220","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"}} -->
<div class="guten-3VVi5m guten-image-box guten-element style-default"><a class="" href="#"><div class="inner-container"><div class="image-box-header"><img class="gutenverse-image-box-filled" src="' . esc_url( OIGNY_LITE_URI ) . 'assets/img/structure-wheel-texture-spiral-number-heart-gradient-368029-pxhere.com_.jpg" height="1800" width="1440" alt="durovo-seo-booster"/></div><div class="image-box-body"><div class="body-inner"></div></div></div></a></div>
<!-- /wp:gutenverse/image-box -->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-785rjm","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}}} -->
<div class="section-wrapper" data-id="785rjm"><section class="wp-block-gutenverse-section guten-element guten-section guten-785rjm layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-3FVUlc"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3FVUlc"><div class="guten-column-wrapper" data-id="3FVUlc"><!-- wp:gutenverse/star-rating {"elementId":"guten-Zqo2v3","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"6CnHAN","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} -->
<div class="guten-element guten-star-rating guten-Zqo2v3"><div class="rating-wrapper"><span class="rating-title">4.4/5</span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating -->

<!-- wp:gutenverse/heading {"elementId":"guten-zyVORO","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"iDPt6e","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-zyVORO">Durovo.</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-0BnmP5","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-0BnmP5"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Content Marketing</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","isChild":true,"gap":"no","elementId":"guten-6sJS4n","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"48","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"right":"50"}}},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"hideTablet":false,"hideMobile":false} -->
<div class="section-wrapper" data-id="6sJS4n"><section class="wp-block-gutenverse-section guten-element guten-section guten-6sJS4n slow layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-3S9wwW","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"85","top":"-150"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-3S9wwW"><div class="guten-column-wrapper" data-id="3S9wwW"><!-- wp:gutenverse/wrapper {"elementId":"guten-xU5RAc","margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"80","left":"80","bottom":"50","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"url":"#"} -->
<div class="guten-element guten-wrap-helper no-margin guten-xU5RAc with-url" onclick="window.open(\'#\', \'undefined\');"><div class="guten-inner-wrap" data-id="xU5RAc"><!-- wp:gutenverse/image-box {"elementId":"guten-k65cDQ","includeButton":false,"url":"#","separateButtonLink":false,"title":"","description":"","hasGlobalLink":true,"image":{"media":{"imageId":16,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"large":{"height":683,"width":1024,"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","orientation":"landscape"},"full":{"url":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp","height":1280,"width":1920,"orientation":"landscape"}}},"size":"full"},"imageAlt":"windr-digital-strategy","imagePadding":{"Desktop":[],"Tablet":[]},"imageMargin":{"Desktop":[]},"imageBorderRadius":{"unit":"px","dimension":{"top":"15","right":"15"}},"imageHeight":{"Desktop":{"point":"320","unit":"px"},"Tablet":{"point":"170","unit":"px"}},"imageFit":"cover","imageHoverOpacity":{"Desktop":""},"imageHoverScale":{"Desktop":"1.1"},"bodyBackground":{"type":"default","color":""},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"all":{"type":"none"},"left":{"type":"none","width":"1"},"bottom":{"type":"none","width":"1"},"right":{"width":"1","type":"none"}},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerMargin":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"titleTypography":{"size":{"Desktop":{"point":"","unit":"px"}},"weight":"400","lineHeight":{"Desktop":{"unit":"em","point":""}},"font":{"label":"Michroma","value":"Michroma","type":"google"}},"titleNormalColor":{"r":255,"g":255,"b":255,"a":1},"descriptionMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descriptionTypography":{"font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"}},"weight":"300","lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"descriptionNormalColor":{"r":200,"g":200,"b":200,"a":1},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"borderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}}},"floatHeight":{"Desktop":""},"floatHeightHover":{"Desktop":""},"imagePosition":{"Desktop":"column"},"lazyLoad":true} -->
<div class="guten-k65cDQ guten-image-box guten-element style-default"><a class="" href="#"><div class="inner-container"><div class="image-box-header"><img class="gutenverse-image-box-filled" src="' . esc_url( OIGNY_LITE_URI ) . 'assets/img/mobile-watch-hand-screen-apple-technology-714160-pxhere.com_.webp" height="1280" width="1920" alt="windr-digital-strategy" loading="lazy"/></div><div class="image-box-body"><div class="body-inner"></div></div></div></a></div>
<!-- /wp:gutenverse/image-box -->

<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-OrPS89","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":"15"}}},"left":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}},"right":{"width":"1","type":"solid","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"65","bottom":"60","left":"65"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"45","right":"45","bottom":"45","left":"45"}}}} -->
<div class="section-wrapper" data-id="OrPS89"><section class="wp-block-gutenverse-section guten-element guten-section guten-OrPS89 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null},"elementId":"guten-5Y1l1R","margin":{"Mobile":[]},"padding":{"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5Y1l1R"><div class="guten-column-wrapper" data-id="5Y1l1R"><!-- wp:gutenverse/star-rating {"elementId":"guten-Y20xCu","title":"4.4/5","align":{"Desktop":"flex-start","Tablet":"flex-start","Mobile":"flex-start"},"starIcon":"fill","rating":5,"total":5,"titleColor":{"type":"variable","id":"theme-0"},"titleTypography":{"type":"variable","id":"6CnHAN","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"500"},"gap":{"Desktop":"8"},"iconSize":{"Desktop":"13","Tablet":"12"},"iconGap":{"Desktop":"3"},"iconColorMarked":{"r":240,"g":173,"b":78,"a":1},"iconColorUnmarked":{"r":228,"g":228,"b":228,"a":1},"border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"5","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}}},"hideTablet":false} -->
<div class="guten-element guten-star-rating guten-Y20xCu"><div class="rating-wrapper"><span class="rating-title">4.4/5</span><div class="rating-icons"><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i><i class="full fa fa-star"></i></div></div></div>
<!-- /wp:gutenverse/star-rating -->

<!-- wp:gutenverse/heading {"elementId":"guten-MM5cfO","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"iDPt6e","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"42","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"500"},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-MM5cfO">Windr.</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-XXoOLK","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-XXoOLK"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Digital Strategy</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/wrapper --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ssJMyE","verticalAlign":"center","margin":{"Tablet":{"unit":"px","dimension":{"top":"60"}},"Mobile":[],"Desktop":{"unit":"px","dimension":{"top":"60"}}},"padding":{"Tablet":[],"Desktop":[]}} -->
<div class="section-wrapper" data-id="ssJMyE"><section class="wp-block-gutenverse-section guten-element guten-section guten-ssJMyE layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-hfNMrY","verticalAlign":{"Desktop":"center","Tablet":"default","Mobile":"center"},"horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hfNMrY"><div class="guten-column-wrapper" data-id="hfNMrY"><!-- wp:gutenverse/text-editor {"elementId":"guten-vkYm5M","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"inline","Mobile":"inline"}} -->
<div class="guten-element gutenverse-text-editor guten-vkYm5M"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">View more projects</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-yk3Usc","content":"Click Here","url":"#","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"showIcon":true,"icon":"gtn gtn-arrow-down-right-line","iconPosition":"after","iconSpacing":{"Desktop":"2"},"iconSize":{"Desktop":{"point":"27","unit":"px"},"Tablet":{"point":"22","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"theme-2"},"iconColor":{"type":"variable","id":"theme-2"},"typography":{"type":"variable","id":"C3z2EQ","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"theme-5"},"hoverTextColor":{"type":"variable","id":"theme-5"},"positioningType":{"Desktop":"inline","Mobile":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-yk3Usc"><a class="guten-button guten-button-sm" href="#"><span>Click Here</span><i class="fa-lg gtn gtn-arrow-down-right-line"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
