<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite 404 Gutenverse Hero', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-xaeexx","heightControl":"fit","background":{"type":"default","image":{"Desktop":{"id":103,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/oigny-bg-hero-home.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"fixed":{"Desktop":true},"videoPlayOnMobile":false},"opacity":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","bottom":""}}},"bottom":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"10","bottom":"10","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<div class="section-wrapper" data-id="xaeexx"><section class="wp-block-gutenverse-section guten-element guten-section guten-xaeexx layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-xpYd83","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"160","top":"160","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"140","bottom":"140"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xpYd83"><div class="guten-column-wrapper" data-id="xpYd83"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-7Sagpv","verticalAlign":"center","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"image":{"Desktop":[]},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"7","right":"6","left":"6"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="7Sagpv"><section class="wp-block-gutenverse-section guten-element guten-section guten-7Sagpv layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-99hRvH","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-99hRvH"><div class="guten-column-wrapper" data-id="99hRvH"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-77mBGs","alignText":{"Desktop":"center"},"titleTag":"h1","text":"404","focusText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"TzEKKr","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"116","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1"}}},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"focusColor":{"type":"variable","id":"GofhMQ"},"focusTypography":{"type":"variable","id":"S1K2IB","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"112","unit":"px"},"Tablet":{"point":"76","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"300","style":"italic"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","top":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-77mBGs guten-data" data-id="77mBGs"><div class="heading-section "><h1 class="heading-title"><span class="heading-title">404</span><span class="heading-focus"></span></h1></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-GnA2IU","alignText":{"Desktop":"center"},"text":"Page Not Found","focusText":".","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-GnA2IU guten-data" data-id="GnA2IU"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Page Not Found</span><span class="heading-focus">.</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Mj9bL8","alignment":{"Tablet":"center","Desktop":"center"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"20","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","right":"20","bottom":"0","left":"20"}},"Tablet":{"unit":"%","dimension":{"right":"5","top":"0","bottom":"0","left":"5"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-Mj9bL8"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Oops! The page you are looking for might have been removed had its name changed or is temporarily unavailable</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-JOOZBT","positioningType":{"Desktop":"inline","Mobile":"full"},"border":{"radius":{"Desktop":[],"Mobile":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":[],"Tablet":[]},"inputPlaceholder":"Search...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]},"inputHeight":{"Desktop":"50","Mobile":""},"inputWidth":{"Desktop":{"0":"4","1":"4","2":"0","point":"500","unit":"px"},"Tablet":{"0":"3","1":"2","2":"0","point":"330","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Mobile":[]},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"color":{"type":"variable","id":"theme-2"},"type":"solid","width":"1"}},"inputBgColorNormal":{"Desktop":{"r":0,"g":0,"b":0,"a":0}},"className":"guten-icon"} -->
<div class="guten-element guten-JOOZBT guten-search guten-icon"><form class="gutenverse-search-form"><input type="search" placeholder="Search..." name="s" class="gutenverse-search gutenverse-search-input"/><!-- wp:gutenverse/button {"elementId":"guten-Aq6Vgw","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100","Desktop":""},"buttonHeight":{"Mobile":"","Desktop":""},"alignButton":{"Desktop":"left","Mobile":"left"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"right":"40","left":"40","top":"14","bottom":"18"}},"Mobile":[]},"buttonBackground":{"color":{"r":4,"g":4,"b":4,"a":0},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"uZWK9Y"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"50","bottom":"50","left":"50"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"15"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"C3z2EQ","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"theme-1"},"hoverTextColor":{"type":"variable","id":"theme-1"}} -->
<div class="guten-element guten-button-wrapper guten-Aq6Vgw"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
