<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Home Gutenverse Feature', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-h8GJ7a","verticalAlign":"center","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"100","bottom":"40","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="h8GJ7a"><section class="wp-block-gutenverse-section guten-element guten-section guten-h8GJ7a layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-shsBSM","backgroundAnimated":{"actions":[]},"verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-shsBSM"><div class="guten-column-wrapper" data-id="shsBSM"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-hw4e42","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"image":{"Desktop":{"id":207,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/bg-gradient.webp"}},"position":{"Desktop":"bottom left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"opacity":"0","backgroundAnimated":{"actions":[]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"6","bottom":"6","right":"5","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="hw4e42"><section class="wp-block-gutenverse-section guten-element guten-section guten-hw4e42 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":42,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"elementId":"guten-GYaJnx","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"right":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"30","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-GYaJnx"><div class="guten-column-wrapper" data-id="GYaJnx"><!-- wp:gutenverse/icon {"elementId":"guten-TOEWs8","icon":"gtn gtn-square-solid","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-TOEWs8 guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-square-solid"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-1MtZsn","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Feature","focusText":"/  Why Choose Us","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"theme-4"},"focusTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-advanced-heading guten-1MtZsn"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Feature</span><span class="heading-focus">/  Why Choose Us</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-ylcNUd","color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"10","right":"0","bottom":"60","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"advanceAnimation":{"actions":[],"anchor":"","smoothness":""}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-ylcNUd">We\'re here to give you effective ideas.</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":58,"Tablet":100,"Mobile":null},"elementId":"guten-Njum02","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-4"}}},"borderResponsive":{"Tablet":{"radius":[],"left":{"width":"","type":"none"}},"Mobile":{"radius":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"","top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Njum02"><div class="guten-column-wrapper" data-id="Njum02"><!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-BMfQgF","border":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"60","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="BMfQgF"><section class="wp-block-gutenverse-section guten-element guten-section guten-BMfQgF layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-Vkw7tm","verticalAlign":{"Desktop":"default","Tablet":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"0","right":"40","top":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"15","bottom":"0","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Vkw7tm"><div class="guten-column-wrapper" data-id="Vkw7tm"><!-- wp:gutenverse/heading {"elementId":"guten-SCnfc2","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"hideDesktop":false} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-SCnfc2 animated guten-element-hide desktop-fadeInLeft">Pro Team</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-aDsPtS","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"35","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"15"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"hideDesktop":false,"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-aDsPtS animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Sit ed perspiciatis unde omnis iste natus error sit voluptatem veritatis iste accusantium aperiam doloremque sed aperiam voluptatem.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":50,"Mobile":null},"elementId":"guten-gcR2dp","verticalAlign":{"Desktop":"default","Tablet":"default"},"margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"40","right":"0","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0","top":"0","right":"0","bottom":"0"}},"Tablet":{"unit":"px","dimension":{"left":"15"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"hideTablet":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-gcR2dp"><div class="guten-column-wrapper" data-id="gcR2dp"><!-- wp:gutenverse/heading {"elementId":"guten-Gb9MT0","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"IJGuA3","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"16","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"},"Tablet":{"unit":"em","point":""},"Mobile":{"unit":"em","point":"1.7"}},"weight":"500"},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"5"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"hideDesktop":false} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-Gb9MT0 animated guten-element-hide desktop-fadeInLeft">Great Experience</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-gNL1sl","alignment":{"Desktop":"left"},"textColor":{"type":"variable","id":"theme-4"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"35","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}},"Tablet":{"unit":"px","dimension":{"top":"15"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"200"},"hideDesktop":false,"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-gNL1sl animated guten-element-hide desktop-fadeInLeft"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Iste sit aperiam ed unde omnis iste natus error sit voluptatem veritatis iste accusantium aperiam doloremque sed aperiam voluptatem.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
