<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite About Gutenverse Stats', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-Js9kW7","verticalAlign":"center","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="Js9kW7"><section class="wp-block-gutenverse-section guten-element guten-section guten-Js9kW7 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-ENqRhF","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ENqRhF"><div class="guten-column-wrapper" data-id="ENqRhF"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-11N6Eu","verticalAlign":"center","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"image":{"Desktop":{"id":207,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/bg-gradient.webp"}},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"4","bottom":"4","right":"5","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="11N6Eu"><section class="wp-block-gutenverse-section guten-element guten-section guten-11N6Eu layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-eXqtWz"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-eXqtWz"><div class="guten-column-wrapper" data-id="eXqtWz"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-DB9MvW","background":{"type":"default","color":"","videoPlayOnMobile":false},"backgroundAnimated":{"actions":[]},"margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","left":"0","top":"0","bottom":"0"}}},"hideDesktop":false} -->
<div class="section-wrapper" data-id="DB9MvW"><section class="wp-block-gutenverse-section guten-element guten-section guten-DB9MvW layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":40,"Tablet":100},"elementId":"guten-YxXojw","verticalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-YxXojw"><div class="guten-column-wrapper" data-id="YxXojw"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-OBIjAx","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Our Stats","focusText":"/  By the Numbers","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"theme-4"},"focusTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-advanced-heading guten-OBIjAx"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Our Stats</span><span class="heading-focus">/  By the Numbers</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":60,"Tablet":100},"elementId":"guten-NPNy5o","border":{"radius":{"Desktop":[],"Tablet":[]},"left":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-4"}},"all":{"color":""}},"borderResponsive":{"Tablet":{"radius":[],"left":{"type":"none"}}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"50","top":"20","bottom":"20"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"40"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-NPNy5o"><div class="guten-column-wrapper" data-id="NPNy5o"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-O9MFV9","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"},"duration":"slow"},"hideDesktop":false} -->
<div class="section-wrapper" data-id="O9MFV9"><section class="wp-block-gutenverse-section guten-element guten-section guten-O9MFV9 slow layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":null},"elementId":"guten-wljhbq","order":{"Mobile":4,"Desktop":1},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start"},"margin":{"Mobile":[],"Desktop":[],"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"padding":{"Mobile":[],"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"left":"0","right":"0"}}},"zIndex":{"Mobile":""}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-wljhbq"><div class="guten-column-wrapper" data-id="wljhbq"><!-- wp:gutenverse/fun-fact {"elementId":"guten-9LjssM","iconType":"none","icon":"fas fa-globe-africa","iconColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"iconBgColor":{"Desktop":{"r":231,"g":60,"b":20,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderResponsive":{"Tablet":{"radius":[]}},"iconSize":{"Desktop":"20"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}},"Tablet":[]},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"25"}},"Tablet":[]},"prefix":"","number":"90","suffix":"","title":"Satisfied clients","showSupper":true,"supper":"%","superColor":{"type":"variable","id":"theme-5"},"superTypography":{"font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"600","spacing":{"Desktop":"0.05"}},"superTop":{"Desktop":"-3"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-1"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-4"}},"numberTypography":{"type":"variable","id":"T2Afs1","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":"12"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[],"Tablet":[]},"background":{"type":"default","color":""},"backgroundHover":{"type":"default","color":""},"border":{"all":{"type":"none","width":"0"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"hideDesktop":false,"hoverBottomColor":{"r":231,"g":60,"b":20,"a":1},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-9LjssM guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="90" data-duration="3500"></span><span class="suffix"></span><sup class="super">%</sup></div><span class="title">Satisfied clients</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.4,"Tablet":null},"elementId":"guten-fkvrcR","order":{"Mobile":2,"Desktop":2},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-fkvrcR"><div class="guten-column-wrapper" data-id="fkvrcR"><!-- wp:gutenverse/fun-fact {"elementId":"guten-36yVfT","iconType":"none","icon":"fas fa-user-check","iconColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"iconBgColor":{"Desktop":{"r":231,"g":60,"b":20,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"20"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"25"}}},"prefix":"","number":"30","suffix":"","title":"Professional Team","showSupper":true,"superColor":{"type":"variable","id":"theme-5"},"superTypography":{"font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"600","spacing":{"Desktop":"0.05"}},"superTop":{"Desktop":"-3"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-1"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-4"}},"numberTypography":{"type":"variable","id":"T2Afs1","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":"12"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[]},"background":{"type":"default","color":""},"backgroundHover":{"type":"default","color":""},"border":{"all":{"type":"none","width":"0"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"hideDesktop":false,"hoverBottomColor":{"r":231,"g":60,"b":20,"a":1},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-36yVfT guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="30" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Professional Team</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.3,"Tablet":null},"elementId":"guten-vHP4rW","order":{"Mobile":3,"Desktop":3},"horizontalAlign":{"Desktop":"flex-end","Tablet":"flex-start"},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"bottom":"20","right":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-vHP4rW"><div class="guten-column-wrapper" data-id="vHP4rW"><!-- wp:gutenverse/fun-fact {"elementId":"guten-2UKaP6","iconType":"none","icon":"fas fa-user-check","iconColor":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"iconBgColor":{"Desktop":{"r":231,"g":60,"b":20,"a":1}},"iconBorder":{"radius":{"Desktop":[]}},"iconBorderHover":{"radius":{"Desktop":[]}},"iconSize":{"Desktop":"20"},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"25"}}},"prefix":"","number":"20","suffix":"","title":"Years of Experience","showSupper":true,"superColor":{"type":"variable","id":"theme-5"},"superTypography":{"font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"22","unit":"px"},"Tablet":{"point":"20","unit":"px"},"Mobile":{"point":"20","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"600","spacing":{"Desktop":"0.05"}},"superTop":{"Desktop":"-3"},"alignButtons":{"Desktop":"left"},"numberColor":{"Desktop":{"type":"variable","id":"theme-1"}},"titleColor":{"Desktop":{"type":"variable","id":"theme-4"}},"numberTypography":{"type":"variable","id":"T2Afs1","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"32","unit":"px"},"Tablet":{"point":"32","unit":"px"},"Mobile":{"point":"32","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"titleTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"numberBottomSpace":{"Desktop":"12"},"titleBottomSpace":{"Desktop":""},"numberRightSpace":{"Desktop":""},"contentPadding":{"Desktop":[],"Mobile":[]},"background":{"type":"default","color":""},"backgroundHover":{"type":"default","color":""},"border":{"all":{"type":"none","width":"0"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"hideDesktop":false,"hoverBottomColor":{"r":231,"g":60,"b":20,"a":1},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-2UKaP6 guten-fun-fact align-center hover-from-left"><div class="fun-fact-inner"><div class="content"><div class="number-wrapper"><span class="prefix"></span><span class="number loaded" data-number="20" data-duration="3500"></span><span class="suffix"></span><sup class="super">+</sup></div><span class="title">Years of Experience</span></div></div></div>
<!-- /wp:gutenverse/fun-fact --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
