<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite About Gutenverse Feature', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-5uSNbb","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":""},"opacity":"0.7","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"80","bottom":"140","right":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="5uSNbb"><section class="wp-block-gutenverse-section guten-element guten-section guten-5uSNbb layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-uUC5qJ","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uUC5qJ"><div class="guten-column-wrapper" data-id="uUC5qJ"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-oeZmA6","verticalAlign":"flex-start","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":"","videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"0","left":"0"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="oeZmA6"><section class="wp-block-gutenverse-section guten-element guten-section guten-oeZmA6 layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-V51HN4","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-V51HN4"><div class="guten-column-wrapper" data-id="V51HN4"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-i1Fdf0","verticalAlign":"flex-start","border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="i1Fdf0"><section class="wp-block-gutenverse-section guten-element guten-section guten-i1Fdf0 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-hSCM1j","margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"95"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"40"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-hSCM1j"><div class="guten-column-wrapper" data-id="hSCM1j"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-kuf4kG","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="section-wrapper" data-id="kuf4kG"><section class="wp-block-gutenverse-section guten-element guten-section guten-kuf4kG layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-L3WXfR"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-L3WXfR"><div class="guten-column-wrapper" data-id="L3WXfR"><!-- wp:gutenverse/icon {"elementId":"guten-jk5aUo","icon":"gtn gtn-square-solid","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"theme-2"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"-2","right":"8","top":"3"}},"Tablet":{"unit":"px","dimension":{"top":"-4","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="wp-block-gutenverse-icon guten-element guten-jk5aUo guten-icon"><span class="guten-icon-wrapper rounded stacked"><i class="gtn gtn-square-solid"></i></span></div>
<!-- /wp:gutenverse/icon -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-xAqVo2","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Feature","focusText":"/ Why Choose Us","subText":"","showSub":"none","showLine":"none","lineWidth":{"Desktop":"6","Mobile":"5","Tablet":"1.5"},"lineHeight":{"Desktop":"9"},"lineMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"","right":"12"}},"Mobile":{"unit":"px","dimension":{"top":"-22"}},"Tablet":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[]},"focusColor":{"type":"variable","id":"theme-3"},"focusTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"left":"15"}},"Tablet":{"unit":"px","dimension":{"right":"","left":"6"}},"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"lineColor":{"type":"variable","id":"ECnqDI"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}},"Mobile":[],"Tablet":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[]},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-advanced-heading guten-xAqVo2"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Feature</span><span class="heading-focus">/ Why Choose Us</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/advanced-heading {"elementId":"guten-kzoQYR","alignText":{"Desktop":"flex-start"},"text":"We bring ideas and stand for","focusText":" {quality}.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"FvbTdd","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":""},"positioningType":{"Desktop":"custom","Tablet":"custom","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"1080","unit":"px"},"Tablet":{"point":"657","unit":"px"}},"advanceAnimation":{"actions":[]}} -->
<div class="guten-element guten-advanced-heading guten-kzoQYR"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">We bring ideas and stand for</span><span class="heading-focus"> {quality}.</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":null},"sectionVerticalAlign":"flex-start","elementId":"guten-4H9wKj","margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-4H9wKj"><div class="guten-column-wrapper" data-id="4H9wKj"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-k8nXDz","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"44","top":"0","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"50","top":"10","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"33","top":"0","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="section-wrapper" data-id="k8nXDz"><section class="wp-block-gutenverse-section guten-element guten-section guten-k8nXDz layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-cdvmmN"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-cdvmmN"><div class="guten-column-wrapper" data-id="cdvmmN"><!-- wp:gutenverse/heading {"elementId":"guten-eziOux","type":3,"textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"background":{"type":"default"},"backgroundHover":{"type":"default","image":{"Desktop":[]}},"border":{"radius":{"Desktop":[]}},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","left":"","top":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"right":"0"}},"Mobile":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"80"},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-eziOux">Our Feature</h3>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-v7dRLo","margin":{"Desktop":{"unit":"px","dimension":{"left":"-20","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"%","dimension":{"left":"0","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":[]},"hideDesktop":false} -->
<div class="section-wrapper" data-id="v7dRLo"><section class="wp-block-gutenverse-section guten-element guten-section guten-v7dRLo layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-yaDwTc","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-yaDwTc"><div class="guten-column-wrapper" data-id="yaDwTc"><!-- wp:gutenverse/icon-list {"elementId":"guten-2J4xn6","spaceBetween":{"Desktop":8},"alignList":{"Desktop":"flex-start"},"iconColor":{"r":255,"g":255,"b":255,"a":0},"iconColorHover":{"type":"variable","id":"theme-5"},"textColor":{"type":"variable","id":"theme-3"},"textColorHover":{"type":"variable","id":"theme-5"},"textTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"}} -->
<div class="guten-element guten-icon-list guten-2J4xn6 animated guten-element-hide desktop-fadeInLeft"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-Q111Ct","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-Q111Ct"><a id="guten-Q111Ct"><i class="gtn gtn-square-solid"></i><span class="list-text ">Best Solution</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-VyQMh1","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-VyQMh1"><a id="guten-VyQMh1"><i class="gtn gtn-square-solid"></i><span class="list-text ">Professional Team</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-yfYdw3","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-yfYdw3"><a id="guten-yfYdw3"><i class="gtn gtn-square-solid"></i><span class="list-text ">Great Experience</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-2h401n","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-2h401n"><a id="guten-2h401n"><i class="gtn gtn-square-solid"></i><span class="list-text ">Fast Response</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-O7xkVa","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-O7xkVa"><a id="guten-O7xkVa"><i class="gtn gtn-square-solid"></i><span class="list-text ">24/7 Support</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
