<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Blog Gutenverse Newsletter', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-v2Xaxo","verticalAlign":"center","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"20","bottom":"20","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="v2Xaxo"><section class="wp-block-gutenverse-section guten-element guten-section guten-v2Xaxo layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"sectionVerticalAlign":"center","elementId":"guten-PdwjaK","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]},"right":{"type":"none","width":"1","color":{"r":237,"g":237,"b":237,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PdwjaK"><div class="guten-column-wrapper" data-id="PdwjaK"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-cfLYbV","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"image":{"Desktop":{"id":207,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/bg-gradient.webp"}},"position":{"Desktop":"bottom left"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"6","bottom":"6","right":"5","left":"5"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="cfLYbV"><section class="wp-block-gutenverse-section guten-element guten-section guten-cfLYbV layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"topSticky":{"Desktop":{"point":"200","unit":"px"}},"elementId":"guten-FjoXzg","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"right":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"50","top":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"","top":"","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-FjoXzg"><div class="guten-column-wrapper" data-id="FjoXzg"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-mcfy6a","alignText":{"Desktop":"flex-start"},"text":"Never miss our post, ","focusText":"subscribe now ","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-1"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"FvbTdd","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"50","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Mobile":"full","Desktop":"custom"},"positioningWidth":{"Desktop":{"point":"690","unit":"px"}},"advanceAnimation":{"actions":[]}} -->
<div class="guten-element guten-advanced-heading guten-mcfy6a"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">Never miss our post, </span><span class="heading-focus">subscribe now </span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-ML2Js1","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Tablet":[]},"left":{"type":"solid","width":"1","color":{"r":119,"g":119,"b":119,"a":1}}},"borderResponsive":{"Tablet":{"radius":[],"left":{"type":"none"}},"Mobile":{"radius":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"30","left":"50"}},"Tablet":{"unit":"px","dimension":{"left":"0","top":"0","right":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0"}}},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ML2Js1"><div class="guten-column-wrapper" data-id="ML2Js1"><!-- wp:gutenverse/form-builder {"elementId":"guten-7HuXld","formId":{"label":"Form Contact","value":338},"hideAfterSubmit":false,"successPadding":{"Desktop":[]},"successBorder":{"radius":{"Desktop":[]}},"errorPadding":{"Desktop":[]},"errorBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-7HuXld" data-form-id="338" data-hide-after="false"><!-- wp:gutenverse/form-input-email {"elementId":"guten-gRRc7b","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"theme-1"}},"labelTypography":{"type":"variable","id":"v72M0U","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","spacing":{"Desktop":"0.08"}},"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"inputLabel":"Your Email Address","inputPlaceholder":"Enter your email address*","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"20","bottom":"16","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"theme-3"}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-1"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-2"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-gRRc7b hide-helper"><div class="label-wrapper"><label class="input-label">Your Email Address</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter your email address*" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-xitmmZ","content":"Subscribe","buttonWidth":{"Desktop":"100"},"buttonBackground":{"type":"default","color":{"r":253,"g":251,"b":251,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-1"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-1"}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-1"}}},"showIcon":true,"icon":"gtn gtn-arrow-down-right-line","iconPosition":"after","iconSpacing":{"Desktop":"15","Mobile":"10"},"iconSize":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"25","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"theme-1"},"iconColor":{"type":"variable","id":"theme-1"},"typography":{"type":"variable","id":"C3z2EQ","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"theme-0"},"hoverTextColor":{"type":"variable","id":"theme-0"},"alignButton":{"Desktop":"flex-start"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"20","bottom":"18","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"14","bottom":"16","right":"20","left":"30"}},"Tablet":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-xitmmZ"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Subscribe</span><i class="fa-lg gtn gtn-arrow-down-right-line"></i></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
