<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Contact Gutenverse Hero', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-gKrKpw","background":{"type":"default","image":{"Desktop":{"id":105,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/bg-hero-page.webp"}},"position":{"Desktop":"custom","Tablet":"center right","Mobile":"center right"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"fixed":{"Desktop":true},"videoPlayOnMobile":false,"gradientColor":[{"color":"rgba(0, 0, 0, 1)","opacity":1,"active":true,"id":1,"offset":"0.093"},{"color":"rgba(168, 20, 231, 1)","active":false,"opacity":1,"id":2,"offset":"0.650"},{"color":"rgba(21, 3, 41, 1)","active":false,"opacity":1,"id":4,"offset":"1.000"}],"gradientType":"linear","gradientAngle":155,"yposition":{"Desktop":{"unit":"%","point":"24"}}},"opacity":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","bottom":""}}},"bottom":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","bottom":"","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<div class="section-wrapper" data-id="gKrKpw"><section class="wp-block-gutenverse-section guten-element guten-section guten-gKrKpw layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-d5fnm8","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"200","bottom":"140","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100","top":"160","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"140","bottom":"100"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-d5fnm8"><div class="guten-column-wrapper" data-id="d5fnm8"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-mUDcF5","verticalAlign":"center","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"image":{"Desktop":[]},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"8","right":"6","left":"6"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="mUDcF5"><section class="wp-block-gutenverse-section guten-element guten-section guten-mUDcF5 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sectionVerticalAlign":"center","elementId":"guten-LZmSbT"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LZmSbT"><div class="guten-column-wrapper" data-id="LZmSbT"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-MSnM4F","alignText":{"Desktop":"flex-start"},"titleTag":"h1","text":"*Connect For","focusText":" {Creative Solutions}.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"UpJPjv","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"82","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"NeJzQY","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"112","unit":"px"},"Tablet":{"point":"76","unit":"px"},"Mobile":{"point":"48","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"style":"italic","weight":"300"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"20","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"0","top":"","bottom":"","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"positioningType":{"Desktop":"custom","Tablet":"full"},"positioningWidth":{"Desktop":{"point":"956","unit":"px"}},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-MSnM4F guten-data" data-id="MSnM4F"><div class="heading-section "><h1 class="heading-title"><span class="heading-title">*Connect For</span><span class="heading-focus"> {Creative Solutions}.</span></h1></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-AhRJPe","alignment":{"Tablet":"left","Desktop":"left"},"textColor":{"type":"variable","id":"theme-3"},"typography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"20","right":"0"}},"Tablet":{"unit":"px","dimension":{"top":"10","right":"","bottom":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"00","top":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"160"},"positioningType":{"Desktop":"default"}} -->
<div class="guten-element gutenverse-text-editor guten-AhRJPe"><div class="text-content-inner"><!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}}} -->
<p style="margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px">Lorem ipsum dolor sit amet consectetur sed consectetur.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
