<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Search Gutenverse Hero', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-2LVv97","background":{"type":"default","image":{"Desktop":{"id":112,"image":"' . esc_url( OIGNY_LITE_URI ) . 'assets/img/bg-hero-page-2.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"r":0,"g":0,"b":0,"a":1},"fixed":{"Desktop":true},"videoPlayOnMobile":false},"opacity":"","border":{"radius":{"Desktop":{"unit":"px","dimension":{"left":"","right":"","bottom":""}}},"bottom":{"type":"none","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","bottom":"","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"35","left":"35"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"20","left":"20"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[]}} -->
<div class="section-wrapper" data-id="2LVv97"><section class="wp-block-gutenverse-section guten-element guten-section guten-2LVv97 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-5C3cVk","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"200","bottom":"140","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"100","top":"160","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"0","right":"0","top":"140","bottom":"100"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-5C3cVk"><div class="guten-column-wrapper" data-id="5C3cVk"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-eHTHtI","verticalAlign":"center","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"image":{"Desktop":[]},"position":{"Desktop":"bottom center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"contain"},"videoPlayOnMobile":false},"opacity":"0","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"18","right":"18","bottom":"18","left":"18"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"7","bottom":"8","right":"6","left":"6"}},"Tablet":{"unit":"px","dimension":{"top":"40","bottom":"40","right":"45","left":"45"}},"Mobile":{"unit":"px","dimension":{"top":"35","bottom":"40","right":"25","left":"25"}}},"zIndex":{"Desktop":""},"hideDesktop":false,"advanceAnimation":{"actions":[],"anchor":"","smoothness":"","pin":false,"pinElement":"guten-KRWuXj"}} -->
<div class="section-wrapper" data-id="eHTHtI"><section class="wp-block-gutenverse-section guten-element guten-section guten-eHTHtI layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"sectionVerticalAlign":"center","elementId":"guten-LQpWnG"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-LQpWnG"><div class="guten-column-wrapper" data-id="LQpWnG"><!-- wp:gutenverse/heading {"elementId":"guten-HKQtkP","textAlign":{"Desktop":"left"},"color":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"UpJPjv","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"82","unit":"px"},"Tablet":{"point":"58","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-HKQtkP">Search Result</h2>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
