<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Oigny Lite Contact Gutenverse Contact', 'oigny-lite' ),
	'categories' => array( 'oigny-lite-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"gap":"no","elementId":"guten-thL29C","background":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":""},"opacity":"0.7","border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"right":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"%","dimension":{"top":"","bottom":"0","right":"12","left":"12"}},"Tablet":{"unit":"px","dimension":{"right":"35","left":"35","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","bottom":"0","left":"20","right":"20"}}},"zIndex":{"Desktop":""},"animation":{"type":{"Desktop":"none"}},"hideDesktop":false} -->
<div class="section-wrapper" data-id="thL29C"><section class="wp-block-gutenverse-section guten-element guten-section guten-thL29C layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-8bcj8E","verticalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"0"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"0","top":"120","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"80","top":"100","left":"0"}},"Mobile":{"unit":"px","dimension":{"left":"","right":"","top":"100","bottom":"80"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8bcj8E"><div class="guten-column-wrapper" data-id="8bcj8E"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"height":{"Desktop":{"point":"804","unit":"px"},"Tablet":{"point":"475","unit":"px"},"Mobile":{"point":"400","unit":"px"}},"gap":"no","elementId":"guten-NQh5BV","verticalAlign":"flex-start","background":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":"","videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"}},"opacity":"0","border":{"radius":{"Desktop":[]},"bottom":{"type":"none","width":"","color":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","bottom":"","right":"0","left":"0"}}},"zIndex":{"Desktop":""},"hideDesktop":false} -->
<div class="section-wrapper" data-id="NQh5BV"><section class="wp-block-gutenverse-section guten-element guten-section guten-NQh5BV layout-fullwidth align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-akRfxC","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"hideTablet":false,"hideMobile":false} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-akRfxC"><div class="guten-column-wrapper" data-id="akRfxC"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-EcJku3","verticalAlign":"flex-start","border":{"all":{"type":"none"},"bottom":{"type":"none"},"top":{"type":"none"},"radius":{"Desktop":[]}},"borderHover":{"all":{"type":"none"},"top":{"type":"none"},"bottom":{"type":"none"},"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","top":"0","right":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"0","left":"0"}}}} -->
<div class="section-wrapper" data-id="EcJku3"><section class="wp-block-gutenverse-section guten-element guten-section guten-EcJku3 layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":70,"Tablet":65,"Mobile":null},"sectionVerticalAlign":"flex-start","elementId":"guten-i1ud3A","margin":{"Desktop":[],"Mobile":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"95"}},"Mobile":{"unit":"px","dimension":{"right":"0","bottom":"60"}},"Tablet":{"unit":"px","dimension":{"right":"50"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-i1ud3A"><div class="guten-column-wrapper" data-id="i1ud3A"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-FlbsHB","alignText":{"Desktop":"flex-start"},"text":"*Contact Us For More","focusText":" Information.","showSub":"none","showLine":"none","lineWidth":{"Desktop":""},"lineHeight":{"Desktop":""},"lineStyle":"solid","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-0"},"mainTypography":{"type":"variable","id":"ENk7Om","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"52","unit":"px"},"Tablet":{"point":"36","unit":"px"},"Mobile":{"point":"24","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":[]},"mainPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"FvbTdd","font":{"label":"Times New Roman","value":"Times New Roman","type":"system"},"size":{"Desktop":{"point":"72","unit":"px"},"Tablet":{"point":"52","unit":"px"},"Mobile":{"point":"36","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"style":"italic","weight":"500"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"0"}},"Tablet":[],"Mobile":[]},"focusPadding":{"Desktop":[],"Tablet":[],"Mobile":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"60","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30"}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"100"},"positioningType":{"Desktop":"custom","Tablet":"full","Mobile":"full"},"positioningWidth":{"Desktop":{"point":"681","unit":"px"},"Tablet":{"point":"486","unit":"px"}},"advanceAnimation":{"actions":[]}} -->
<div class="guten-element guten-advanced-heading guten-FlbsHB animated guten-element-hide desktop-fadeInLeft"><div class="heading-section "><h2 class="heading-title"><span class="heading-title">*Contact Us For More</span><span class="heading-focus"> Information.</span></h2></div></div>
<!-- /wp:gutenverse/advanced-heading -->

<!-- wp:gutenverse/form-builder {"elementId":"guten-JsvmMP","formId":{"label":"Form Contact","value":338},"hideAfterSubmit":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}} -->
<form style="display:none" class="guten-element guten-form-builder guten-JsvmMP" data-form-id="338" data-hide-after="false"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":1170},"isChild":true,"gap":"no","elementId":"guten-hsUl1f","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"4"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="hsUl1f"><section class="wp-block-gutenverse-section guten-element guten-section guten-hsUl1f layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-96Xzvx","margin":{"Desktop":{"unit":"px","dimension":{"right":"20","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-96Xzvx"><div class="guten-column-wrapper" data-id="96Xzvx"><!-- wp:gutenverse/form-input-text {"elementId":"guten-kyBkqR","inputLabel":" Your Name","inputPlaceholder":"Enter your fullname*","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"theme-3"}},"labelTypography":{"type":"variable","id":"v72M0U","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","spacing":{"Desktop":"0.08"}},"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","left":"20","right":"20"}},"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"r":60,"g":60,"b":60,"a":1}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Tablet":[]},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-2"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-kyBkqR hide-helper"><div class="label-wrapper"><label class="input-label"> Your Name</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter your fullname*" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-ESoRsm","margin":{"Desktop":{"unit":"px","dimension":{"right":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"left":"10"}}},"padding":{"Desktop":[],"Mobile":[],"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ESoRsm"><div class="guten-column-wrapper" data-id="ESoRsm"><!-- wp:gutenverse/form-input-email {"elementId":"guten-kdofvE","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"theme-3"}},"labelTypography":{"type":"variable","id":"v72M0U","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","spacing":{"Desktop":"0.08"}},"displayLogic":[],"labelPadding":{"Desktop":{"unit":"px","dimension":{"bottom":"","top":"","right":"","left":""}}},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"helperPadding":{"Desktop":[]},"inputLabel":"Your Email","inputPlaceholder":"Enter your email address*","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"20","bottom":"16","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"r":60,"g":60,"b":60,"a":1}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-2"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-kdofvE hide-helper"><div class="label-wrapper"><label class="input-label">Your Email</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Enter your email address*" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-MKksj2","inputLabel":"Subject","inputPlaceholder":"Write your subject*","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"theme-3"}},"labelTypography":{"type":"variable","id":"v72M0U","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","spacing":{"Desktop":"0.08"}},"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","bottom":"16","left":"20","right":"20"}},"Tablet":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"0"}}},"placeholderColor":{"Desktop":{"r":60,"g":60,"b":60,"a":1}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}},"Tablet":[]},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"inputBorderHover":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-2"}}},"inputBorderFocus":{"radius":{"Desktop":[]},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-5"}}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-MKksj2 hide-helper"><div class="label-wrapper"><label class="input-label">Subject</label></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Write your subject*" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-7P2UOg","showHelper":false,"labelColor":{"Desktop":{"type":"variable","id":"theme-3"}},"labelTypography":{"type":"variable","id":"v72M0U","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"weight":"500","spacing":{"Desktop":"0.08"}},"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":{"unit":"px","dimension":{"bottom":"10"}}},"helperPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"inputHeight":{"Desktop":"140"},"inputLabel":"Message","inputPlaceholder":"Write your message*","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"16","right":"20","bottom":"16","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"r":60,"g":60,"b":60,"a":1}},"inputTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"theme-0"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"all":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}},"bottom":{"width":"1","color":"","type":"solid"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"bottom":{"type":"solid","width":"1","color":""},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-2"}}},"inputColorFocus":{"Desktop":{"r":255,"g":255,"b":255,"a":1}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"8","right":"8","bottom":"8","left":"8"}}},"bottom":{"type":"solid","width":"1","color":""},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"theme-5"}}},"inputBgColorNormal":{"Desktop":{"r":60,"g":60,"b":60,"a":0}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-7P2UOg hide-helper"><div class="label-wrapper"><label class="input-label">Message</label></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Write your message*" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-N4qekH","content":"Send Message","buttonWidth":{"Desktop":"","Mobile":"100"},"buttonBackground":{"type":"default","color":{"r":253,"g":251,"b":251,"a":0}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"theme-0"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"15","bottom":"15","left":"15"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"buttonBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}},"all":{"type":"solid","width":"1","color":{"r":255,"g":255,"b":255,"a":1}}},"showIcon":true,"icon":"gtn gtn-arrow-down-right-line","iconPosition":"after","iconSpacing":{"Desktop":"15","Mobile":"8"},"iconSize":{"Desktop":{"point":"32","unit":"px"},"Mobile":{"point":"26","unit":"px"}},"border":{"radius":{"Desktop":[]}},"borderHover":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]},"color":{"type":"variable","id":"theme-0"},"iconColor":{"type":"variable","id":"theme-0"},"typography":{"type":"variable","id":"C3z2EQ","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.05"},"weight":"600"},"hoverIconColor":{"type":"variable","id":"theme-1"},"hoverTextColor":{"type":"variable","id":"theme-1"},"alignButton":{"Desktop":"flex-start"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"14","right":"20","bottom":"18","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"14","bottom":"16","right":"20","left":"20"}},"Tablet":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-N4qekH"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span><i class="fa-lg gtn gtn-arrow-down-right-line"></i></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":30,"Tablet":35},"sectionVerticalAlign":"flex-start","elementId":"guten-8Ve7FA","margin":{"Tablet":{"unit":"px","dimension":{"top":"8"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-8Ve7FA"><div class="guten-column-wrapper" data-id="8Ve7FA"><!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-I0jTDE","border":{"radius":{"Desktop":[]},"bottom":{"type":"solid","width":"1","color":{"r":60,"g":60,"b":60,"a":1}}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"30","top":"5","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"bottom":"30","top":"0","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="section-wrapper" data-id="I0jTDE"><section class="wp-block-gutenverse-section guten-element guten-section guten-I0jTDE layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-DmmzWB"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-DmmzWB"><div class="guten-column-wrapper" data-id="DmmzWB"><!-- wp:gutenverse/advanced-heading {"elementId":"guten-HvLH1q","alignText":{"Desktop":"flex-start"},"titleTag":"h3","text":"Contact Info","focusText":".","showSub":"none","showLine":"none","lineMargin":{"Desktop":[]},"mainColor":{"type":"variable","id":"theme-3"},"mainTypography":{"type":"variable","id":"K8rf8i","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"mainMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"mainPadding":{"Desktop":[],"Tablet":[]},"focusColor":{"type":"variable","id":"theme-2"},"focusTypography":{"type":"variable","id":"ce9oFN","font":{"label":"Michroma","value":"Michroma","type":"google"},"size":{"Desktop":{"point":"24","unit":"px"},"Tablet":{"point":"18","unit":"px"},"Mobile":{"point":"18","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"},"Mobile":{"unit":"em","point":"1.4"}},"weight":"600"},"focusMargin":{"Desktop":{"unit":"px","dimension":{"top":"","left":"2"}}},"focusPadding":{"Desktop":[]},"subMargin":{"Desktop":[]},"subPadding":{"Desktop":[]},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]},"advanceAnimation":{"type":"scroll","actions":[]},"className":"guten-data"} -->
<div class="guten-element guten-advanced-heading guten-HvLH1q guten-data" data-id="HvLH1q"><div class="heading-section "><h3 class="heading-title"><span class="heading-title">Contact Info</span><span class="heading-focus">.</span></h3></div></div>
<!-- /wp:gutenverse/advanced-heading --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"layout":"fullwidth","width":{"Desktop":"1200"},"isChild":true,"gap":"no","elementId":"guten-FNwtef","margin":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":[]},"padding":{"Desktop":{"unit":"%","dimension":{"left":"0","top":"","right":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"left":"0"}},"Tablet":[]},"hideDesktop":false} -->
<div class="section-wrapper" data-id="FNwtef"><section class="wp-block-gutenverse-section guten-element guten-section guten-FNwtef layout-fullwidth align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":100,"Mobile":null},"elementId":"guten-CrLhhL","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CrLhhL"><div class="guten-column-wrapper" data-id="CrLhhL"><!-- wp:gutenverse/icon-list {"elementId":"guten-ejlsB4","spaceBetween":{"Desktop":"20","Mobile":"10","Tablet":"6"},"alignList":{"Desktop":"flex-start"},"iconColor":{"type":"variable","id":"theme-2"},"iconColorHover":{"type":"variable","id":"theme-2"},"iconSize":{"Desktop":"12","Tablet":"9"},"textColor":{"type":"variable","id":"theme-3"},"textColorHover":{"type":"variable","id":"theme-2"},"textIndent":{"Tablet":"","Desktop":"10"},"textTypography":{"type":"variable","id":"xSXxly","font":{"label":"Montserrat","value":"Montserrat","type":"google"},"size":{"Desktop":{"point":"18","unit":"px"},"Tablet":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}},"weight":"300"},"margin":{"Desktop":[],"Tablet":[],"Mobile":{"unit":"px","dimension":{"left":"0"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]}} -->
<div class="guten-element guten-icon-list guten-ejlsB4"><!-- wp:gutenverse/icon-list-item {"elementId":"guten-i4RBZl","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-i4RBZl"><a id="guten-i4RBZl"><i class="fas fa-clock"></i><span class="list-text ">Mon-Sat : 8:00 AM – 5:00 PM</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ZAOyzg","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-ZAOyzg"><a id="guten-ZAOyzg"><i class="fas fa-map-marker-alt"></i><span class="list-text ">Jl. Sunset Road No.815, Bali</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-APQaG2","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-APQaG2"><a id="guten-APQaG2"><i class="fas fa-phone"></i><span class="list-text ">+62 361 154874</span></a></div>
<!-- /wp:gutenverse/icon-list-item -->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-6AoyNx","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-icon-list-item guten-6AoyNx"><a id="guten-6AoyNx"><i class="fas fa-envelope"></i><span class="list-text ">support@example.com</span></a></div>
<!-- /wp:gutenverse/icon-list-item --></div>
<!-- /wp:gutenverse/icon-list --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
);
